"""Initial migration

Revision ID: 541c30f17d78
Revises: 3230916bc511
Create Date: 2024-09-12 15:51:42.176384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541c30f17d78'
down_revision: Union[str, None] = '3230916bc511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('glass_general_price', sa.Float(), nullable=True),
    sa.Column('shipping_glass_supplier_price', sa.Float(), nullable=True),
    sa.Column('aluminum_frame_price', sa.Float(), nullable=True),
    sa.Column('stainless_steel_price', sa.Float(), nullable=True),
    sa.Column('local_shipping_price', sa.Float(), nullable=True),
    sa.Column('paint_al_frame_price', sa.Float(), nullable=True),
    sa.Column('cut_assemble_frame_price', sa.Float(), nullable=True),
    sa.Column('setting_block_price', sa.Float(), nullable=True),
    sa.Column('install_glass_price', sa.Float(), nullable=True),
    sa.Column('fix_cost_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('sitetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitename', sa.String(), nullable=True),
    sa.Column('site_location', sa.String(), nullable=True),
    sa.Column('site_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitetable_id'), 'sitetable', ['id'], unique=False)
    op.create_index(op.f('ix_sitetable_sitename'), 'sitetable', ['sitename'], unique=False)
    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('linear_foot', sa.Float(), nullable=True),
    sa.Column('square_foot', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sitetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_id'), 'quotation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_id'), table_name='quotation')
    op.drop_table('quotation')
    op.drop_index(op.f('ix_sitetable_sitename'), table_name='sitetable')
    op.drop_index(op.f('ix_sitetable_id'), table_name='sitetable')
    op.drop_table('sitetable')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
