"""create users table

Revision ID: 1e0a9714cc67
Revises: b7874efb97ab
Create Date: 2024-11-19 10:40:59.566455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0a9714cc67'
down_revision: Union[str, None] = 'b7874efb97ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
