"""create users table

Revision ID: 2f95bf4a9bde
Revises: 8cd92c7ab572
Create Date: 2024-11-07 18:33:37.886356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f95bf4a9bde'
down_revision: Union[str, None] = '8cd92c7ab572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('quotation', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotation', 'quotation', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotation', type_='foreignkey')
    op.drop_column('quotation', 'parent_id')
    op.drop_column('quotation', 'version')
    # ### end Alembic commands ###
