"""create users table

Revision ID: 3812212cd9e7
Revises: 55be43b145f5
Create Date: 2024-11-29 08:28:00.261554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3812212cd9e7'
down_revision: Union[str, None] = '55be43b145f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitetable', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sitetable', 'last_updated')
    # ### end Alembic commands ###
