"""create users table

Revision ID: 465bd54def05
Revises: 1e0a9714cc67
Create Date: 2024-11-21 06:18:26.380637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465bd54def05'
down_revision: Union[str, None] = '1e0a9714cc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'updated_at')
    op.drop_column('quotation', 'created_at')
    # ### end Alembic commands ###
