"""create users table

Revision ID: 5b7f024dfb88
Revises: 465bd54def05
Create Date: 2024-11-21 06:40:46.187086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7f024dfb88'
down_revision: Union[str, None] = '465bd54def05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotation_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_history', 'updated_at')
    op.drop_column('quotation_history', 'created_at')
    # ### end Alembic commands ###
