"""create users table

Revision ID: 6b7eb4cf2f6b
Revises: 1fdb6c35fed0
Create Date: 2024-10-25 05:32:54.068121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7eb4cf2f6b'
down_revision: Union[str, None] = '1fdb6c35fed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
