"""create users table

Revision ID: 9b514dfc5778
Revises: ca23350080ef
Create Date: 2024-11-08 06:20:22.332767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b514dfc5778'
down_revision: Union[str, None] = 'ca23350080ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('custom_shape', sa.String(), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('linear_foot', sa.Float(), nullable=True),
    sa.Column('square_foot', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_history_id'), 'quotation_history', ['id'], unique=False)
    op.drop_constraint('quotation_parent_id_fkey', 'quotation', type_='foreignkey')
    op.drop_column('quotation', 'parent_id')
    op.drop_column('quotation', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quotation', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('quotation_parent_id_fkey', 'quotation', 'quotation', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_quotation_history_id'), table_name='quotation_history')
    op.drop_table('quotation_history')
    # ### end Alembic commands ###
