"""create users table

Revision ID: b7b84ce1628d
Revises: 0cbec827125a
Create Date: 2024-11-08 07:00:13.944372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b84ce1628d'
down_revision: Union[str, None] = '0cbec827125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_history', 'product_id')
    op.drop_column('quotation_history', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_history', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_history', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
