"""create users table

Revision ID: ca23350080ef
Revises: 2f95bf4a9bde
Create Date: 2024-11-07 19:15:21.607399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca23350080ef'
down_revision: Union[str, None] = '2f95bf4a9bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'is_active')
    # ### end Alembic commands ###
